### ISSUE TITLE
请问SmsSingleSender.send()方法不能使用了吗?

### ISSUE THREAD

**Issue by nicholaspangpang** [qcloudsms/qcloudsms_java#16]
SmsSingleSender.send()方法不能使用了吗?
现在好像都要制定短信模板id了是吗？
不能再自己组装短信内容了是不是？

**Comment by nicholaspangpang** [comment]
如果不让用了，请取消这个方法哈，或者告知一下如何使用自定义的短信内容。

**Comment by sxyseo** [comment]
可以用的。
开始也不能用，后面切到1.0.5可以用了，之后就切回来到1.0.6也正常了。

**Comment by lcb1208** [comment]
> 可以用的。
> 开始也不能用，后面切到1.0.5可以用了，之后就切回来到1.0.6也正常了。

没模板ID能发？

**Comment by weijunyi** [comment]
升级新版本的 SDK，请直接使用模板 ID 进行发送，使用短信全文内容进行发送的协议后面可能不在支持。
