### ISSUE TITLE
安卓使用sdk的问题

### ISSUE THREAD

**Issue by ShunyangLi** [qcloudsms/qcloudsms_java#20]
当安卓使用sdk的时候会有冲突，希望能给予解决方法    java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)

**Comment by qcloudsms** [comment]
您好，一般来说我们 SDK 运行的环境是服务端，Android 的环境和 Java 服务端环境有些差异，对这些差异的兼容并不是我们的目标，请您谅解。
