### ISSUE TITLE
指定模板ID单发短信 这个demo代码有问题

### ISSUE THREAD

**Issue by zen-liutao** [qcloudsms/qcloudsms_java#6]
String[] params = {"5678"};
 SmsSingleSender ssender = new SmsSingleSender(appid, appkey);
 SmsSingleSenderResult result = sendWithParam("86", phoneNumbers[0],
templateId, params, smsSign, "", "");  // 签名参数未提供或者为空时，会使用默认签名发送短信
上面的方法应该是ssender.sendWithParam()
虽然不是什么大问题，但是还是要注意一点

**Comment by luwanding** [comment]
需要注意

**Comment by qcloudsms** [comment]
@zen-liutao @luwanding 您好，已修复
