### ISSUE TITLE
sdk在Springboot下报错

### ISSUE THREAD

**Issue by Venus-WXP** [qcloudsms/qcloudsms_java#7]
java.lang.NoSuchMethodError: org.json.JSONObject.put(Ljava/lang/String;Ljava/util/Collection;)Lorg/json/JSONObject;

**Comment by qcloudsms** [comment]
您好，应该是包冲突的问题，请检查一下是否与其他版本的org.json冲突

**Comment by BJming** [comment]
java.lang.NoSuchMethodError: org.json.JSONObject.put(Ljava/lang/String;Ljava/util/Collection;)Lorg/json/JSONObject;

**Comment by BJming** [comment]
SpringBoot 1.5.10.RELEASE环境下使用qcloud单发模板短信功能，发生报错，该Maven环境下未显式引入其他json jar包，望贵官方处理好和SpringBoot的冲突问题， 大厂出现此种问题不应该

**Comment by qcloudsms** [comment]
@BJming 这个是包依赖冲突问题，`qcloudsms_java` 不能考虑到跟其他所有第三方依赖冲突问题，这个需要用户主动来解决，解决方法可以参考  https://github.com/qcloudsms/qcloudsms_java/wiki/maven解决org.json冲突示例

**Comment by jiulinxiri** [comment]
终于找到怎么解决的了 @qcloudsms

**Comment by 847850277** [comment]
公司用spring-boot项目也出了同样问题，写了一个扩展类来解决

import com.alibaba.fastjson.JSONObject;
import com.github.qcloudsms.SmsSenderUtil;
import com.github.qcloudsms.SmsSingleSender;
import com.github.qcloudsms.SmsSingleSenderResult;
import com.github.qcloudsms.httpclient.*;
import org.json.JSONException;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by zhengpeng on 2018/5/31.
 * 扩展腾讯云发送短信方法
 * 因为腾讯云引用json的包与spring-boot有冲突，故自己来实现
 */
public class MySmsSingleSender extends SmsSingleSender {

    private String url = "https://yun.tim.qq.com/v5/tlssmssvr/sendsms";

    public MySmsSingleSender(int appid, String appkey) {
        super(appid, appkey);
    }

    public MySmsSingleSender(int appid, String appkey, HTTPClient httpclient) {
        super(appid, appkey, httpclient);
    }

    @Override
    public SmsSingleSenderResult sendWithParam(String nationCode, String phoneNumber, int templateId, String[] params, String sign, String extend, String ext) throws HTTPException, JSONException, IOException {
        return this.sendWithParam(nationCode, phoneNumber, templateId, new ArrayList(Arrays.asList(params)), sign, extend, ext);
    }

    @Override
    public SmsSingleSenderResult sendWithParam(String nationCode, String phoneNumber, int templateId, ArrayList<String> params, String sign, String extend, String ext) throws HTTPException, JSONException, IOException {


        long random = SmsSenderUtil.getRandom();
        long now = SmsSenderUtil.getCurrentTime();
        //JSONObject body = (new JSONObject()).put("tel", (new JSONObject()).put("nationcode", nationCode).put("mobile", phoneNumber)).put("sig", SmsSenderUtil.calculateSignature(this.appkey, random, now, phoneNumber)).put("tpl_id", templateId).put("params", params).put("sign", sign).put("time", now).put("extend", SmsSenderUtil.isNotEmpty(extend)?extend:"").put("ext", SmsSenderUtil.isNotEmpty(ext)?ext:"");
        //扩展方法 使用fastjson
        /**
         *入参
         *
         {
         "ext": "",
         "extend": "",
         "params": [
         "验证码",
         "1234",
         "4"
         ],
         "sig": "ecab4881ee80ad3d76bb1da68387428ca752eb885e52621a3129dcf4d9bc4fd4",
         "sign": "腾讯云",
         "tel": {
         "mobile": "13788888888",
         "nationcode": "86"
         },
         "time": 1457336869,
         "tpl_id": 19
         }
         *
         *
         */

        JSONObject body = new JSONObject();
        Map telMap = new HashMap<>();
        telMap.put("mobile",phoneNumber);
        telMap.put("nationcode",nationCode);
        body.put("tel",telMap);
        body.put("params",params);
        body.put("tpl_id",templateId);
        body.put("sig",SmsSenderUtil.calculateSignature(this.appkey, random, now, phoneNumber));
        body.put("sign", sign);
        body.put("time",now);
        body.put("extend", SmsSenderUtil.isNotEmpty(extend)?extend:"");
        body.put("ext", SmsSenderUtil.isNotEmpty(ext)?ext:"");


        HTTPRequest req = (new HTTPRequest(HTTPMethod.POST, this.url)).addHeader("Conetent-Type", "application/json").addQueryParameter("sdkappid", this.appid).addQueryParameter("random", random).setConnectionTimeout('\uea60').setRequestTimeout('\uea60').setBody(body.toString());

        try {
            HTTPResponse e = this.httpclient.fetch(req);
            this.handleError(e);
            return (new SmsSingleSenderResult()).parseFromHTTPResponse(e);
        } catch (URISyntaxException var15) {
            throw new RuntimeException("API url has been modified, current url: " + this.url);
        }
    }
}

**Comment by lees5488** [comment]
【引用】_这个属于包依赖冲突问题，qcloudsms_java 不能考虑到跟所有其他第三方依赖冲突问题，这个需要用户主动来解决，解决方法可以参考这里 https://github.com/qcloudsms/qcloudsms_java/wiki/maven解决org.json冲突示例_


**这个方法不能治本**
