### ISSUE TITLE
根据模板单发在SpringBoot2.0中无法使用

### ISSUE THREAD

**Issue by jitwxs** [qcloudsms/qcloudsms_java#8]
java.lang.NoSuchMethodError: org.json.JSONObject.put(Ljava/lang/String;Ljava/util/Collection;)Lorg/json/JSONObject;
	at com.github.qcloudsms.SmsSingleSender.sendWithParam(SmsSingleSender.java:111)

**Comment by qcloudsms** [comment]
您好，应该是包冲突的问题，请检查一下是否与其他版本的`org.json`冲突

**Comment by qcloudsms** [comment]
解决方法可以参考这里 https://github.com/qcloudsms/qcloudsms_java/wiki/maven解决org.json冲突示例

**Comment by jitwxs** [comment]
已成功解决

**Comment by bootsrc** [comment]
也遇到相同的问题。 按照上方的答复， 已解决。
